### ISSUE TITLE
euniceylee/waves - Dependency problems

### ISSUE THREAD

**Issue by pgcorbett** [euniceylee/waves#1]
Hi,

I've got to the stage where my Pi is communicating with the printer just fine.  The next bit is
"To get the code working, you can first clone our repository. We require a few dependencies: time, matplotlib, FFMPEG, PIL, subprocess, and Flask. To get those working, just run pip install dependency."

I've cloned the repository with 
git clone https://github.com/euniceylee/waves

then
sudo apt-get install python-pip
pip install dependency

pip install dependency appears to stall, and has done for about a day now.
I tried to install the dependencies individually, but time is not found, matplotlib fails, and FFMPEG stalls.

I'm new to python, so I'm probably doing something obviously wrong.  Any ideas what?

Thanks.

**Comment by bomanimc** [comment]
Hey @pgcorbett! Thanks for giving this a shot.

**time**
The `time` dependency comes stock with Python, which may explain the difficulty that `pip` is having in finding it (and is something we need to update in our documentation). Given this, you should be able to skip installing this package.

**matplotlib**
What is the exact error that you get trying to install `matplotlib`? I forgot exactly what we did, but I have a few ideas. Try out the following approaches:

_Approach 1_: Try out installing `matplotlib` using `sudo apt-get install python-matplotlib` instead of `pip`, as taken from their [Linux installation guide](https://matplotlib.org/users/installing.html).

_Approach 2_: Try running `sudo apt-get install libpulse-dev` and `sudo apt-get install python-dev` before attempting to install `matplotlib` with `sudo apt-get install python-matplotlib`, as instructed by [this Stack Overflow response](https://stackoverflow.com/questions/43613666/pip-install-matplotlib-fails-on-raspbian-jessie-4-4).

_Approach 3_: If the other strategies fail, you may be able to build and install `matplotlib` using the approach that user whyvas figured out in [this issue](https://github.com/matplotlib/basemap/issues/274).

**ffmpeg**
We ended up needing to follow [these instructions](https://www.jeffreythompson.org/blog/2014/11/13/installing-ffmpeg-for-raspberry-pi/) to get ffmpeg to install correctly. It takes a while to install (a few hours max). 

---

Thanks for testing this out! This has illuminated some areas of lacking detail in our documentation that we will update upon hearing how these strategies work for you. We'll be as responsive as possible as you go through the process, and we're excited to help you get your setup working! 

Please let me know if these things help!

**Comment by pgcorbett** [comment]
Thanks for getting back to me.

Your suggestions got my dependencies working fine.  I just needed to install pydub using sudo pip install pydub, as controller.py complained about it being missing.

When I get chance I'll wire it all up, and I look forward to trying it out!

**Comment by bomanimc** [comment]
Awesome @pgcorbett. Which approach to installing `matplotlib` worked for you?

**Comment by pgcorbett** [comment]
Sorry about the late response.  Approach 2 worked for me.
